#!/usr/bin/env python3
"""Check model registry configuration and how to invoke functions"""

import sys
sys.path.insert(0, '/home/ec2-user/localllmstuff/MEETING_TRANSCRIPTION_AGENT/snowflake_call_transcript_and_speaker_detection/spcs_service')

import json
from snowflake.snowpark import Session
from snowflake.ml.registry import Registry
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

# Load private key
with open("/home/ec2-user/.snowflake/rsa_key.p8", "rb") as key_file:
    private_key = serialization.load_pem_private_key(
        key_file.read(),
        password=None,
        backend=default_backend()
    )

connection_params = {
    "account": "SFSEEUROPE-DWESSENDORF_AZURE1_WESTEU",
    "user": "DWESSENDORF",
    "private_key": private_key,
    "warehouse": "CALL_TRANSCRIPTS_WH",
    "database": "CALL_TRANSCRIPTS_DB",
    "schema": "TRANSCRIPTS",
    "role": "ACCOUNTADMIN"
}

session = Session.builder.configs(connection_params).create()

# Get registry and model version
registry = Registry(session, database_name="CALL_TRANSCRIPTS_DB", schema_name="TRANSCRIPTS")
model = registry.get_model("SPEAKER_EMBEDDING")
mv = model.version("V11")

print("=" * 60)
print("MODEL VERSION INFO")
print("=" * 60)
print(f"Model: {model.name}")
print(f"Version: {mv.version_name}")

# Check service details  
services = mv.list_services()
print(f"\nServices DataFrame:\n{services.to_string()}")

# Get internal endpoint
svc_name = services.iloc[0]['name']
print(f"\nService name: {svc_name}")

# Try to get service info
print("\n" + "=" * 60)
print("SERVICE LOGS")
print("=" * 60)
try:
    logs = mv.get_service_logs(service_name=svc_name.split('.')[-1])
    print(f"Logs: {logs[:2000]}...")
except Exception as e:
    print(f"Error getting logs: {e}")

# Check how to call functions - using model inference
print("\n" + "=" * 60)
print("SQL TO CALL MODEL")
print("=" * 60)

# Try using the model call syntax
try:
    # The model version can generate SQL for calling functions
    sql = f"""
    SELECT * FROM TABLE(
        CALL_TRANSCRIPTS_DB.TRANSCRIPTS.SPEAKER_EMBEDDING:V11::HEALTH(
            OBJECT_CONSTRUCT('dummy', 'test')
        )
    )
    """
    print(f"Testing SQL: {sql}")
    result = session.sql(sql).collect()
    print(f"Result: {result}")
except Exception as e:
    print(f"Error: {e}")

# Get the function SQL pattern from model version
print("\n" + "=" * 60) 
print("MODEL INVOKE SQL PATTERN")
print("=" * 60)
try:
    # Check model_version_client approach
    from snowflake.ml.model._client.sql import model_version as mv_sql
    
    # Get the SQL generated by model version
    print(f"Model ops: {mv._model_ops}")
    print(f"Model version client: {mv._model_ops._model_version_client}")
except Exception as e:
    print(f"Error: {e}")

# Try SNOWFLAKE.ML schema for models
print("\n" + "=" * 60)
print("TRY SNOWFLAKE.ML MODELS")
print("=" * 60)
try:
    result = session.sql("SHOW MODELS IN SCHEMA SNOWFLAKE.ML").collect()
    print(f"Models in SNOWFLAKE.ML: {result}")
except Exception as e:
    print(f"Error: {e}")

# Check registry internal
print("\n" + "=" * 60)
print("REGISTRY INFO")
print("=" * 60)
print(f"Registry database: {registry._database_name}")
print(f"Registry schema: {registry._schema_name}")

# List all objects in the schema
print("\n" + "=" * 60)
print("OBJECTS IN SCHEMA")
print("=" * 60)
try:
    result = session.sql("""
        SELECT TABLE_NAME, TABLE_TYPE 
        FROM INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_SCHEMA = 'TRANSCRIPTS' 
        AND TABLE_NAME LIKE '%SPEAKER%'
    """).collect()
    for row in result:
        print(f"  {row['TABLE_TYPE']}: {row['TABLE_NAME']}")
except Exception as e:
    print(f"Error: {e}")

session.close()
