-- ============================================================================
-- Snowflake Speaker Detection - Table Creation
-- ============================================================================
-- Creates all required tables for the speaker detection solution
-- ============================================================================

USE SCHEMA MEETING_AGENT_DB.MEETING_AGENT;

-- ============================================================================
-- SPEAKERS - Registry of known speakers
-- ============================================================================
CREATE TABLE IF NOT EXISTS SPEAKERS (
    SPEAKER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    DISPLAY_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200),
    DEPARTMENT VARCHAR(100),
    COMPANY VARCHAR(200),
    NOTES VARCHAR(2000),
    IS_INTERNAL BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    METADATA VARIANT
);

-- ============================================================================
-- MEETINGS - Meeting metadata and status
-- ============================================================================
CREATE TABLE IF NOT EXISTS MEETINGS (
    MEETING_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    TITLE VARCHAR(500),
    MEETING_DATE DATE,
    MEETING_TIME TIME,
    DURATION_MINUTES NUMBER,
    MEETING_TYPE VARCHAR(100),
    RECORDING_PATH VARCHAR(500),
    TRANSCRIPTION_PATH VARCHAR(500),
    TRANSCRIPTION_STATUS VARCHAR(50) DEFAULT 'pending',
    CLASSIFICATION_STATUS VARCHAR(50) DEFAULT 'pending',
    TOTAL_SPEAKERS NUMBER,
    IDENTIFIED_SPEAKERS NUMBER DEFAULT 0,
    UNIDENTIFIED_SPEAKERS NUMBER DEFAULT 0,
    LANGUAGE VARCHAR(10),
    SUMMARY VARCHAR(5000),
    ACTION_ITEMS VARIANT,
    PARTICIPANTS VARIANT,
    TAGS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    METADATA VARIANT
);

-- ============================================================================
-- SPEAKER_PROFILES - Voice profile data (not currently used, for future)
-- ============================================================================
CREATE TABLE IF NOT EXISTS SPEAKER_PROFILES (
    PROFILE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SPEAKER_ID VARCHAR(50) NOT NULL REFERENCES SPEAKERS(SPEAKER_ID),
    PROFILE_TYPE VARCHAR(50) DEFAULT 'voice',
    EMBEDDING VECTOR(FLOAT, 192),
    SAMPLE_AUDIO_PATH VARCHAR(500),
    SAMPLE_DURATION_SECONDS FLOAT,
    QUALITY_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA VARIANT
);

-- ============================================================================
-- MEETING_CONTRIBUTIONS - Individual speech segments from meetings
-- ============================================================================
CREATE TABLE IF NOT EXISTS MEETING_CONTRIBUTIONS (
    CONTRIBUTION_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    MEETING_ID VARCHAR(50) NOT NULL REFERENCES MEETINGS(MEETING_ID),
    SEGMENT_NUMBER NUMBER NOT NULL,
    DIARIZATION_LABEL VARCHAR(20),
    IDENTIFIED_SPEAKER_ID VARCHAR(50) REFERENCES SPEAKERS(SPEAKER_ID),
    IDENTIFICATION_METHOD VARCHAR(50),
    IDENTIFICATION_CONFIDENCE FLOAT,
    MATCHED_PROFILE_ID VARCHAR(50) REFERENCES SPEAKER_PROFILES(PROFILE_ID),
    AUDIO_SNIPPET_PATH VARCHAR(500),
    EMBEDDING VECTOR(FLOAT, 192),
    TEXT_CONTENT VARCHAR(100000),
    START_TIME_SECONDS FLOAT,
    END_TIME_SECONDS FLOAT,
    DURATION_SECONDS FLOAT,
    WORD_COUNT NUMBER,
    CLASSIFICATION_STATUS VARCHAR(50) DEFAULT 'pending',
    CLASSIFICATION_CONFIDENCE FLOAT,
    REVIEWED_AT TIMESTAMP_NTZ,
    REVIEWED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA VARIANT
);

-- ============================================================================
-- CLASSIFICATION_QUEUE - Queue for speaker classification workflow
-- ============================================================================
CREATE TABLE IF NOT EXISTS CLASSIFICATION_QUEUE (
    QUEUE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    MEETING_ID VARCHAR(50) NOT NULL REFERENCES MEETINGS(MEETING_ID),
    CONTRIBUTION_ID VARCHAR(50) NOT NULL REFERENCES MEETING_CONTRIBUTIONS(CONTRIBUTION_ID),
    DIARIZATION_LABEL VARCHAR(20),
    SUGGESTED_SPEAKER_ID VARCHAR(50),
    SUGGESTED_SPEAKER_NAME VARCHAR(200),
    SUGGESTION_CONFIDENCE FLOAT,
    ALTERNATIVE_SUGGESTIONS VARIANT,
    AUDIO_SNIPPET_PATH VARCHAR(500),
    SNIPPET_DURATION_SECONDS FLOAT,
    TEXT_PREVIEW VARCHAR(1000),
    STATUS VARCHAR(50) DEFAULT 'pending',
    PRIORITY NUMBER DEFAULT 5,
    ASSIGNED_TO VARCHAR(100),
    ASSIGNED_AT TIMESTAMP_NTZ,
    SELECTED_SPEAKER_ID VARCHAR(50),
    CREATED_NEW_SPEAKER BOOLEAN DEFAULT FALSE,
    NEW_PROFILE_CREATED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ,
    COMPLETED_BY VARCHAR(100),
    METADATA VARIANT
);

-- ============================================================================
-- SPEAKER_VOICEPRINTS - Voice embeddings for speaker identification
-- ============================================================================
CREATE TABLE IF NOT EXISTS SPEAKER_VOICEPRINTS (
    SPEAKER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SPEAKER_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200),
    DEPARTMENT VARCHAR(100),
    EMBEDDING VECTOR(FLOAT, 192),
    SAMPLE_AUDIO_PATH VARCHAR(500) NOT NULL,
    SAMPLE_DURATION_SECONDS FLOAT,
    ENROLLMENT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    QUALITY_SCORE FLOAT,
    METADATA VARIANT
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_contributions_meeting ON MEETING_CONTRIBUTIONS(MEETING_ID);
CREATE INDEX IF NOT EXISTS idx_contributions_speaker ON MEETING_CONTRIBUTIONS(IDENTIFIED_SPEAKER_ID);
CREATE INDEX IF NOT EXISTS idx_queue_meeting ON CLASSIFICATION_QUEUE(MEETING_ID);
CREATE INDEX IF NOT EXISTS idx_queue_status ON CLASSIFICATION_QUEUE(STATUS);

-- Verify tables created
SHOW TABLES IN SCHEMA MEETING_AGENT_DB.MEETING_AGENT;
